EXP_NAME: pama
SEED: 3407

DATASET:
  datadir: 'datasets\MVTec'
  texture_source_dir: 'datasets\dtd\images'
  target: 'screw'
  resize: !!python/tuple
    - 256 # height
    - 256 # width
  structure_grid_size: 8
  transparency_range:
    - 0.15 # under bound
    - 1. # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 16
  num_workers: 4

MEMORYBANK:
  nb_memory_sample: 1

MODEL:
  feature_extractor_name: 'resnet34'

TRAIN:
  batch_size: 16
  num_training_steps: 5000
  l1_weight: 0
  focal_weight: 1
  focal_alpha: null
  focal_gamma: 4
  use_wandb: True

OPTIMIZER:
  lr: 0.003
  weight_decay: 0.0005

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: True

LOG:
  log_interval: 1
  eval_interval: 100

RESULT:
  savedir: './saved_model'